
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR COMMA DOUBLE EQUALS FLOAT IDENTIFIER INT SEMICOLONdeclaracion : tipo lista_identificadores SEMICOLON\n                   | tipo EQUALS lista_identificadores SEMICOLONtipo : INT\n             | FLOAT\n             | CHAR\n             | DOUBLElista_identificadores : IDENTIFIER\n                              | lista_identificadores COMMA IDENTIFIER'
    
_lr_action_items = {'INT':([0,],[3,]),'FLOAT':([0,],[4,]),'CHAR':([0,],[5,]),'DOUBLE':([0,],[6,]),'$end':([1,10,14,],[0,-1,-2,]),'EQUALS':([2,3,4,5,6,],[8,-3,-4,-5,-6,]),'IDENTIFIER':([2,3,4,5,6,8,11,],[9,-3,-4,-5,-6,9,13,]),'SEMICOLON':([7,9,12,13,],[10,-7,14,-8,]),'COMMA':([7,9,12,13,],[11,-7,11,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaracion':([0,],[1,]),'tipo':([0,],[2,]),'lista_identificadores':([2,8,],[7,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaracion","S'",1,None,None,None),
  ('declaracion -> tipo lista_identificadores SEMICOLON','declaracion',3,'p_declaracion_variable','syntax.py',6),
  ('declaracion -> tipo EQUALS lista_identificadores SEMICOLON','declaracion',4,'p_declaracion_variable','syntax.py',7),
  ('tipo -> INT','tipo',1,'p_tipo','syntax.py',11),
  ('tipo -> FLOAT','tipo',1,'p_tipo','syntax.py',12),
  ('tipo -> CHAR','tipo',1,'p_tipo','syntax.py',13),
  ('tipo -> DOUBLE','tipo',1,'p_tipo','syntax.py',14),
  ('lista_identificadores -> IDENTIFIER','lista_identificadores',1,'p_lista_identificadores','syntax.py',18),
  ('lista_identificadores -> lista_identificadores COMMA IDENTIFIER','lista_identificadores',3,'p_lista_identificadores','syntax.py',19),
]
